1.write a function called Humpty_Dumpty that takes a number .If the number is divisible by 3. it should return "Humpty",if it is divisible by 5. it should return "Dumpty". if it is divisible by both 3 and 5 ,it should return the same number

2.write a program whicg reads 2 matrices of3*2 and 2*3 respectively and perform matrix multiplication

3.wite a function that returns the sum of multiples of 3 and 5 between - and limit(parameter).For example ,if limit is 20, it should return the sum of 3,5,6,9,10,12,15,18,20

4.write a python program to demonstrate the folloeing conditions:
  read data from .txt file
  plot the data using suitable plots
  fit a linear line assuming 'm'(slope)and 'c'(offset/bias)

In [ ]:
def Humpty_Dumpty(number):
    if number % 3 == 0 and number % 5 == 0:
        return number
    elif number % 3 == 0:
        return "Humpty"
    elif number % 5 == 0:
        return "Dumpty"
    else:
        return number

# Example usage:
num = int(input("Enter a number: "))
result = Humpty_Dumpty(num)
print(result)


Enter a number: 5
Dumpty


In [1]:
import numpy as np


def read_matrix(rows, cols):
    matrix = []
    for i in range(rows):
        row = []
        for j in range(cols):
            element = float(input(f"Enter element at ({i+1}, {j+1}): "))
            row.append(element)
        matrix.append(row)
    return np.array(matrix)


print("Enter the first matrix (3x2):")
matrix1 = read_matrix(3, 2)


print("\nEnter the second matrix (2x3):")
matrix2 = read_matrix(2, 3)


result = np.dot(matrix1, matrix2)


print("\nMatrix multiplication result (3x3):")
print(result)



Enter the first matrix (3x2):
Enter element at (1, 1): 1
Enter element at (1, 2): 2
Enter element at (2, 1): 3
Enter element at (2, 2): 4
Enter element at (3, 1): 5
Enter element at (3, 2): 1

Enter the second matrix (2x3):
Enter element at (1, 1): 4
Enter element at (1, 2): 5
Enter element at (1, 3): 6
Enter element at (2, 1): 8
Enter element at (2, 2): 9
Enter element at (2, 3): 10

Matrix multiplication result (3x3):
[[20. 23. 26.]
 [44. 51. 58.]
 [28. 34. 40.]]


In [ ]:
8def sum_multiples_of_3_and_5(limit):
    result = 0

    for num in range(1, limit + 1):
        if num % 3 == 0 or num % 5 == 0:
            result += num

    return result

# Example usage:
limit = 20
total_sum = sum_multiples_of_3_and_5(limit)
print(f"The sum of multiples of 3 and 5 between 1 and {limit} is: {total_sum}")


The sum of multiples of 3 and 5 between 1 and 20 is: 98
