Functions
1.Define the function
2.Invoking the function
3.Passing the arguments

In [ ]:
def cake_baker(p,f,s):
  print("No of pieces=",p)
  print("Flavour is=",p)
  print("size is=",s)

cake_baker("5","Chocolate","2kg")
cake_baker("100","vanilla","3kg")

No of pieces= 5
Flavour is= 5
size is= 2kg
No of pieces= 100
Flavour is= 100
size is= 3kg


In [ ]:
def cake_baker(p,f,s):
  print("No of pieces=",p)
  print("Flavour is=",p)
  print("size is=",s)

cake_baker("5","Chocolate","2kg",toppings)
cake_baker("100","vanilla","3kg")

NameError: ignored

In [ ]:
def add(*args):
  sum=0
  for i in args:
   sum+=i
  return sum
print(add(1,2,3,4,5))

15


In [ ]:
def add(*bunch):
  sum=0
  for i in bunch:
   sum+=i
  return sum
print(add(1,2,3,4,5))

15


In [ ]:
def greet(**kwargs):
  print("Hello")
  for key,value in kwargs.items():
    print(value, end="")

greet(name="kavya",usn="kj3034",branch="ECE")


Hello
kavyakj3034ECE

In [ ]:
import random

x=random.randint(1,9)
print(x)

a=random.random
print(a)

2
<built-in method random of Random object at 0x5bb12ccc8120>


In [ ]:
import random

computer=random.randint(1,9)
userinput=int(input("Enter the number between 1 and 9"))
print(computer)
print(userinput)

if computer>userinput:
  print("Computer Won")
elif computer==userinput:
  print("TIF")
else:
 print("You won")

Enter the number between 1 and 99
7
9
You won


In [ ]:
import random

gamelist=['rock','paper','scissors']
z=random.choice(gamelist)
user=input("Enter either rock or paper or scissors ")
print(comp)
print(user)

if(comp=="rock"and user=="paper"):
  print("computer won")
elif(comp=="paper" and user=="scissors"):
  print("You won")
elif(comp=="scissor"and user=="paper"):
  print("Computer won")

  else:

SyntaxError: ignored

Numpy- Numerical Python

In [ ]:
import numpy as np


In [ ]:
a=np.array([35,1,34,36,27,48,49])
print(type(a))

b=np.zeros(3)
c=np.ones(4)

print(b)
print(c)

d=np.sort(a)
print(d)

<class 'numpy.ndarray'>
[0. 0. 0.]
[1. 1. 1. 1.]
[ 1 27 34 35 36 48 49]
